// Suggestions uniquement : l'utilisateur peut toujours saisir librement le nom de son établissement.
export const UNIVERSITIES: string[] = [
  // Bénin
  "Université d'Abomey-Calavi (UAC)",
  "Université de Parakou (UP)",
  "Université Nationale des Sciences, Technologies, Ingénierie et Mathématiques (UNSTIM)",
  "Institut National Supérieur de Physique Expérimentale et Interdisciplinaire (INSPEI/UNSTIM)",
  "Université Nationale d'Agriculture (UNA)",
  "École Polytechnique d'Abomey-Calavi (EPAC)",
  "Faculté des Sciences et Techniques (FAST/UAC)",
  "Institut de Formation et de Recherche en Informatique (IFRI)",
  "Institut de Mathématiques et de Sciences Physiques (IMSP)",
  "École Nationale d'Économie Appliquée et de Management (ENEAM)",
  "École Nationale Supérieure de Génie Mathématique et Modélisation (ENSGMM)",
  "Institut Universitaire de Technologie de Lokossa",
  "Université Catholique de l'Afrique de l'Ouest (UCAO-UUC Cotonou)",
  "Université Africaine de Technologie et de Management (UATM)",
  "ESGIS Bénin",
  "Institut Sainte Félicité",
  // Afrique de l'Ouest francophone
  "Université de Lomé",
  "Université de Kara",
  "Université Cheikh Anta Diop de Dakar (UCAD)",
  "Université Gaston Berger de Saint-Louis (UGB)",
  "Université Félix Houphouët-Boigny (Abidjan)",
  "Institut National Polytechnique Félix Houphouët-Boigny (INP-HB)",
  "Université Joseph Ki-Zerbo (Ouagadougou)",
  "Université Nazi Boni (Bobo-Dioulasso)",
  "Université des Sciences, des Techniques et des Technologies de Bamako (USTTB)",
  "Université Abdou Moumouni (Niamey)",
  "Université Gamal Abdel Nasser de Conakry",
  "Université de Nouakchott",
  // Afrique centrale
  "Université de Yaoundé I",
  "Université de Douala",
  "Université Marien Ngouabi (Brazzaville)",
  "Université Omar Bongo (Libreville)",
  "Université de Kinshasa",
  "Université de Lubumbashi",
  // Afrique anglophone
  "University of Ghana",
  "Kwame Nkrumah University of Science and Technology (KNUST)",
  "University of Lagos",
  "University of Ibadan",
  "Obafemi Awolowo University",
  "University of Nairobi",
  "Makerere University",
  "University of Dar es Salaam",
  "University of Cape Town",
  "University of the Witwatersrand",
  "Stellenbosch University",
  "University of Rwanda",
  "African Institute for Mathematical Sciences (AIMS)",
  "African Leadership University",
  // Afrique du Nord
  "Université Mohammed V de Rabat",
  "Université Cadi Ayyad (Marrakech)",
  "Université Mohammed VI Polytechnique (UM6P)",
  "Université de Tunis El Manar",
  "Université des Sciences et de la Technologie Houari Boumediene (USTHB)",
  "Cairo University",
  "Autre établissement",
];
